apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts-service
  namespace: kindcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alerts-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: alerts-service
        version: v1
    spec:
      containers:
        - name: alerts-service
          image: 923080620566.dkr.ecr.us-east-1.amazonaws.com/kindcare/alerts-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: kindcare-db-secret
                  key: host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: kindcare-db-secret
                  key: name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: kindcare-db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kindcare-db-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
