grafana:
  adminPassword: KindCare2024x
  service:
    type: ClusterIP
  assertNoLeakedSecrets: false
  envFromSecret: grafana-github-secret
  sidecar:
    datasources:
      defaultDatasourceEnabled: false

  grafana.ini:
    server:
      domain: grafana.mariamdevops.com
      root_url: https://grafana.mariamdevops.com
    auth:
      disable_login_form: true
      oauth_auto_login: true
    auth.github:
      enabled: true
      allow_sign_up: true
      client_id: Ov23liKtO63ry1qPDqf1
      client_secret: $__env{GF_AUTH_GITHUB_CLIENT_SECRET}
      scopes: user:email,read:org
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      api_url: https://api.github.com/user
      role_attribute_path: "'GrafanaAdmin'"
      allow_assign_grafana_admin: true
      skip_org_role_sync: true

prometheus:
  prometheusSpec:
    retention: 15d

alertmanager:
  config:
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.ethereal.email:587'
      smtp_from: 'buford.wolff@ethereal.email'
      smtp_auth_username: 'buford.wolff@ethereal.email'
      smtp_auth_password: 'wB3V8wFcxHUBNtG6KV'
      smtp_require_tls: true
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'email'
    receivers:
      - name: 'email'
        email_configs:
          - to: 'mntendo@dons.usfca.edu'
            send_resolved: true
      - name: 'null'
