name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        description: 'AWS Access Key ID from Vocareum'
        required: true
      aws_secret_access_key:
        description: 'AWS Secret Access Key from Vocareum'
        required: true
      aws_session_token:
        description: 'AWS Session Token from Vocareum'
        required: true
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id || secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key || secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ github.event.inputs.aws_session_token || secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Build and push images
        env:
          AWS_REGION: us-east-1
          IMAGE_TAG: ${{ github.ref_name }}
        run: bash scripts/01-build-images.sh

      - name: Update manifests
        env:
          AWS_REGION: us-east-1
          IMAGE_TAG: ${{ github.ref_name }}
        run: bash scripts/02-update-manifests.sh

      - name: Deploy to EKS
        env:
          AWS_REGION: us-east-1
          ENVIRONMENT: dev
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST_DEV }}
        run: bash scripts/04-deploy-to-eks.sh

      - name: Smoke test
        run: bash scripts/05-smoke-test.sh

      - name: Production smoke test
        env:
          PROD_URL: https://kindcare.mariamdevops.com
        run: bash scripts/prod-smoke-test.sh

      - name: Notify
        env:
          ENVIRONMENT: production
          IMAGE_TAG: ${{ github.ref_name }}
        run: bash scripts/06-notify.sh
